spring:
  application:
    name: demo

  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://weucathsursqlf03.postgres.database.azure.com:5432/ocean_surcharge?currentSchema=public
    username: psqladmin
    password: no4jLYr3QKkSUlez3mTpF"b"5ImCrpTF
    hikari:
      max-lifetime: 2000000
    driver-class-name: org.postgresql.Driver

  # JPA Configuration for PostgreSQL
  # Solr Configuration
  data:
#    solr:
#      base-url: https://athena-solr-cdt.maersk-digital.net/solr
#      core-name: unnumbers
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update       # Auto-create or update database schema (use 'none' for production)
      show-sql: true           # Show SQL queries in the logs
      properties:
        hibernate.format_sql: true
        hibernate.transaction.coordinator_class: org.hibernate.transaction.JDBCTransactionFactory

server:
  port: 8080  # Spring Boot server port
