version: '3.8'
services:
  logstash:
    container_name: logstash
    build: ./logstash/.
    volumes:
      - ./logstash/config/pipeline/:/usr/share/logstash/config/pipelines/
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
    # command: logstash -f /logstash_dir/ports.conf
#    depends_on:
#      - solr
#      - postgres
    ports:
      - 9600:9600
      - 5044:5044
    environment:
      - xpack.monitoring.enabled=false
      - "LS_JAVA_OPTS=-Xmx1024m -Xms512m"
      - "LOGSTASH_JDBC_DRIVER_JAR_LOCATION=/usr/share/logstash/logstash-core/lib/jars/postgresql.jar"
    networks:
      - my_network

#  postgres:
#    image: postgres
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: psqladmin
#      POSTGRES_PASSWORD: no4jLYr3QKkSUlez3mTpF"b"5ImCrpTF
#      POSTGRES_DB: public
#    volumes:
#      - database-data:/var/lib/postgresql/data:rw

#  solr:
#    container_name: demosample1
#    image: solr:8.11
#    ports:
##      - 8983
#      - 8983:8983
#    volumes:
#      - solr-data:/var/solr
#    environment:
#      - SOLR_HOME=/var/solr
##    command: ["solr-precreate", "unnumbers"]
#    networks:
#      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  solr-data:
  database-data:
